# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-29 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('IdContactos', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_completo', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=150)),
                ('Comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('IdSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=60)),
                ('Apellido', models.CharField(max_length=60)),
                ('Paquete', models.CharField(max_length=90)),
                ('Correo', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=40)),
                ('Fecha', models.DateField()),
                ('Comentarios', models.TextField()),
            ],
        ),
    ]
