# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-29 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('IdTicket', models.IntegerField(primary_key=True, serialize=False)),
                ('Usuario', models.CharField(max_length=100)),
                ('FechaAbierto', models.DateField()),
                ('Correo', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=50)),
                ('Problema', models.CharField(max_length=90)),
                ('ExplicacionProblema', models.TextField()),
            ],
        ),
    ]
